export const DEFAULT_LANGUAGE = 'ru';

export const SET_COUNTRIES_LIST = 'SET_COUNTRIES_LIST';
export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_USER = 'SET_USER';
export const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_USER_CURRENCIES_LIST = 'SET_USER_CURRENCIES_LIST';
export const SET_THEME = 'SET_THEME';

